apply plugin: 'com.android.application'
android {
    compileSdk 34
    namespace 'com.cryptosignal.aipro'
    defaultConfig {
        applicationId "com.cryptosignal.aipro"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }
    buildTypes {
        release { minifyEnabled false }
        debug { minifyEnabled false }
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
dependencies { }